# Generated by Django 2.2.24 on 2022-01-23 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_app_plan_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='planid',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='planid',
        ),
        migrations.AddField(
            model_name='subscription',
            name='app',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='plan',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
